title: "Sherie's Blog"
author: "Sherie Lin"
description: "Portfolio of Sherie - Data Scientist specializing in machine learning, cloud-based data pipelines, and predictive analytics. <b style=\"color: #f45;\">&lt;3</b>"
keywords: "data scientist, clean energy, analytics, time series, big data, cloud computing, Python, PowerBI, R, Tableau"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon} I added title and icon
  - {file: "/", title: "Home", icon: home} #index.html
  - {file: "/assets/resume/resume.pdf", title: "Resume", icon: address-card}
  - {title: "My GitHub", file: "https://github.com/Pinghsuanlin"}
  - {file: "blog.md", title: "Blog"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "sherrylinl111@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/Pinghsuanlin"}
  - {title: LinkedIn, icon: linkedin, url: "https://linkedin.com/in/pinghsuanlin"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
